// Generated types from OpenAPI specification
// This file will be auto-generated by the gen:types script

export interface HealthResponse {
  status: string;
  time: string;
  version: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface LoginResponse {
  access_token: string;
  refresh_token: string;
  user: {
    id: number;
    email: string;
    name: string;
  };
}

export interface RefreshRequest {
  refresh_token: string;
}

export interface RefreshResponse {
  access_token: string;
  refresh_token: string;
}

export interface User {
  id: number;
  email: string;
  name: string;
  role: 'USER' | 'ADMIN' | 'MODERATOR';
  createdAt: string;
  updatedAt: string;
}

export interface Category {
  id: number;
  name: string;
  description?: string;
  slug: string;
  createdAt: string;
  updatedAt: string;
}

export interface Thread {
  id: number;
  title: string;
  content: string;
  slug: string;
  isSticky: boolean;
  isLocked: boolean;
  createdAt: string;
  updatedAt: string;
  authorId: number;
  categoryId: number;
  author?: User;
  category?: Category;
}

export interface Post {
  id: number;
  content: string;
  createdAt: string;
  updatedAt: string;
  authorId: number;
  threadId: number;
  author?: User;
  thread?: Thread;
}
